package Entity;
// Generated Dec 30, 2017 3:24:26 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private String name;
     private String address;
     private String phone;
     private Double salary;
     private String position;
     private Date createdAt;
     private int delFlag;

    public Employee() {
    }

	
    public Employee(String username, String password, Date createdAt, int delFlag) {
        this.username = username;
        this.password = password;
        this.createdAt = createdAt;
        this.delFlag = delFlag;
    }
    public Employee(String username, String password, String name, String address, String phone, Double salary, String position, Date createdAt, int delFlag) {
       this.username = username;
       this.password = password;
       this.name = name;
       this.address = address;
       this.phone = phone;
       this.salary = salary;
       this.position = position;
       this.createdAt = createdAt;
       this.delFlag = delFlag;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Double getSalary() {
        return this.salary;
    }
    
    public void setSalary(Double salary) {
        this.salary = salary;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public int getDelFlag() {
        return this.delFlag;
    }
    
    public void setDelFlag(int delFlag) {
        this.delFlag = delFlag;
    }




}


