package Entity;
// Generated Nov 24, 2017 1:39:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail  implements java.io.Serializable {


     private Integer id;
     private int orderId;
     private int dishId;
     private int quanlity;
     private BigDecimal price;
     private Date createdAt;
     private int delFlag;

    public OrderDetail() {
    }

    public OrderDetail(int orderId, int dishId, int quanlity, BigDecimal price, Date createdAt, int delFlag) {
       this.orderId = orderId;
       this.dishId = dishId;
       this.quanlity = quanlity;
       this.price = price;
       this.createdAt = createdAt;
       this.delFlag = delFlag;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public int getDishId() {
        return this.dishId;
    }
    
    public void setDishId(int dishId) {
        this.dishId = dishId;
    }
    public int getQuanlity() {
        return this.quanlity;
    }
    
    public void setQuanlity(int quanlity) {
        this.quanlity = quanlity;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public int getDelFlag() {
        return this.delFlag;
    }
    
    public void setDelFlag(int delFlag) {
        this.delFlag = delFlag;
    }




}


